#!r6rs
(library (test repl)
  (export main)
  (import (rnrs (6))
          (rime logging logger)
          )
  (define (main)
    (logger :trace "hello world 1" 1 2 3)
    (logger :trace "hello world 2")
    (logger :trace "hello world 3")))
