(library (test test-vector)
  (export test-vector)
  (import (rnrs (6))
          (skeme loop)
          (skeme protobuf private vec)
          (skeme protobuf private test)
          (skeme protobuf private display))
  (define test-vector #t)
  (define-test
    test-vec-create-vector
    (define v (vec 1 2 3))
    (check equal? (vec-length v) 3)
    (vec-set! v 0 0)
    (vec-set! v 1 1)
    (vec-set! v 2 2)
    (check vec-equal? v (vec 0 1 2))
    (check equal? (vec-ref v 0) 0)
    (check equal? (vec-ref v 1) 1)
    (check equal? (vec-ref v 2) 2)
    (check equal? (vec->list v) (list 0 1 2))
    (vec-fill! v 0)
    (check equal? (vec->list v) (list 0 0 0))
    (vec-for-each (lambda (x) (display-objects "x=" x "\n")) v)
    (check vec-equal? (vec-map + (vec 0 1 2) (vec 3 4 5))
           (vec 3 5 7))
    (set! v (vec 0 1 2))
    (vec-append v 3 4 5)
    (check vec-equal? v
           (vec 0 1 2 3 4 5))
    ))
