name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
         submodules: 'true'

    - name: Install chezscheme
      run: sudo apt-get install -y chezscheme guile-3.0

    - name: make
      run: make

    - name: test with guile
      run: make test-guile

    - name: test with chez
      run: make test-chez
