name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
   Run-on-Ubuntu:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
         submodules: 'true'

    - name: Install chezscheme and guile
      run: sudo apt-get install -y chezscheme guile-3.0

    - name: make
      run: make

    - name: test with chez
      run: make test-chez

    - name: test with guile
      run: make test-guile

   Run-on-Macos:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
         submodules: 'true'

    - name: Install chezscheme and guile
      run: brew install chezscheme guile

    - name: make
      run: make

    - name: test with chez
      run: make test-chez

    - name: test with guile
      run: make test-guile
